MassageParlor/Entities/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MassageParlor.Entities
{
    public class Employee
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }

        [Required]
        public DateTime StartDate { get; set; }

        [MaxLength(200)]
        public string Description { get; set; }

       // public ICollection<EmployeeMassage> MassageServices { get; set; } = new List<EmployeeMassage>();
    }
}

MassageParlor/Entities/EmployeeMassage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace MassageParlor.Entities
{
    public class EmployeeMassage
    {
        [Key]
        public Guid Id { get; set; }

        public Guid EmployeeId { get; set; }

        [ForeignKey("EmployeeId")]
        public Employee Employee { get; set; }

        public Guid MassageId { get; set; }

        [ForeignKey("MassageId")]
        public Massage Massage { get; set; }
    }
}

MassageParlor/Entities/Massage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MassageParlor.Entities
{
    public class Massage
    {
        [Key]
        public Guid Id { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        public ICollection<EmployeeMassage> EmployeesThatPerformThis { get; set; } = new List<EmployeeMassage>();

    }
}

MassageParlor/Models/ErrorViewModel.cs
using System;

namespace MassageParlor.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MassageParlor/Models/MassagesViewModel.cs
namespace MassageParlor.Models
{
    public class MassagesViewModel
    {
        public string Name { get; set; }

        public string Description { get; set; }
    }
}

MassageParlor/Models/MasseuesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MassageParlor.Models
{
    public class MasseuesViewModel
    {
        public string Name { get; set; }

        public string Description { get; set; }

        public DateTime StartDate { get; set; }

        //public List<MassagesViewModel> MassagesProvided { get; set; }
    }
}

MassageParlor/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MassageParlor.Models;

namespace MassageParlor.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MassageParlor/Controllers/MassageController.cs
using MassageParlor.Models;
using MassageParlor.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace MassageParlor.Controllers
{
    public class MassageController : Controller
    {
        IMassageService _massageService;

        public MassageController(IMassageService massageService)
        {
            _massageService = massageService;
        }

        public IActionResult Index()
        {
            IEnumerable<MassagesViewModel> massages = _massageService.GetMassages();
            return View(massages);
        }
    }
}

MassageParlor/Controllers/MasseuseController.cs
using System;
using System.Collections.Generic;
using AutoMapper;
using MassageParlor.Entities;
using MassageParlor.Models;
using MassageParlor.Services;
using Microsoft.AspNetCore.Mvc;

namespace MassageParlor.Controllers
{
    public class MasseuseController : Controller
    {
        private readonly IMassageService _massage;

        public MasseuseController(IMassageService massage)
        {
            _massage = massage;
        }

        public IActionResult Index()
        {
            IEnumerable<MasseuesViewModel> employees = _massage.GetEmployeesForViewing();

            return View(employees);
        }
    }
}

MassageParlor/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MassageParlor/Views/Massage/Index.cshtml
@model IEnumerable<MassageParlor.Models.MassagesViewModel>

@{
    ViewData["Title"] = "Massages";
}

<h1>Massages Provided</h1>

@*<p>
    <a asp-action="Create">Create New</a>
</p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            @*<td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>*@
        </tr>
}
    </tbody>
</table>

MassageParlor/Views/Masseuse/Index.cshtml
@model IEnumerable<MassageParlor.Models.MasseuesViewModel>

@{
    ViewData["Title"] = "Masseuses";
}

<html>
<head>
    <link rel="stylesheet" href="~/css/massues.css" />
</head>
<body>

    <h1>Masseuses</h1>

    @*<p>
            <a asp-action="Create">Create New</a>
        </p>*@

    @foreach (var massues in Model)
    {
        <div id="Employee" style="border:solid">
            <p>
                @Html.DisplayFor(modelItem => massues.Name) <br>
                @Html.DisplayFor(modelItem => massues.Description) <br>
                @Html.DisplayFor(modelItem => massues.StartDate) <br>
            </p>
        </div>
        @*<div>
            future expansion idea click name and revial information about employees
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#Employee">@Html.DisplayFor(modelItem => massues.Name)</button>
            <div id="Employee" class="collapse">
                <p>
                    @Html.DisplayFor(modelItem => massues.Description)
                </p>
                <p>
                    @Html.DisplayFor(modelItem => massues.StartDate)
                </p>
            </div>
            <br id="employeeSpliter">*@
    }
</body>
</html>

MassageParlor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MassageParlor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MassageParlor</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Masseuse" asp-action="Index">Masseuses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Massage" asp-action="Index">Massages</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MassageParlor - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>